# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jtzhuang/projects/stable-diffusion.cpp/wan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jtzhuang/projects/stable-diffusion.cpp/wan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtzhuang/projects/stable-diffusion.cpp/wan/CMakeFiles /home/jtzhuang/projects/stable-diffusion.cpp/wan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jtzhuang/projects/stable-diffusion.cpp/wan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wan-cpp

# Build rule for target.
wan-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wan-cpp
.PHONY : wan-cpp

# fast build rule for target.
wan-cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/build
.PHONY : wan-cpp/fast

#=============================================================================
# Target rules for targets named ggml-base

# Build rule for target.
ggml-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base
.PHONY : ggml-base

# fast build rule for target.
ggml-base/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml-base.dir/build.make ggml/src/CMakeFiles/ggml-base.dir/build
.PHONY : ggml-base/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml.dir/build.make ggml/src/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml-cpu

# Build rule for target.
ggml-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu
.PHONY : ggml-cpu

# fast build rule for target.
ggml-cpu/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml-cpu.dir/build.make ggml/src/CMakeFiles/ggml-cpu.dir/build
.PHONY : ggml-cpu/fast

#=============================================================================
# Target rules for targets named zip

# Build rule for target.
zip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zip
.PHONY : zip

# fast build rule for target.
zip/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/CMakeFiles/zip.dir/build.make thirdparty/CMakeFiles/zip.dir/build
.PHONY : zip/fast

#=============================================================================
# Target rules for targets named wan-cli

# Build rule for target.
wan-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wan-cli
.PHONY : wan-cli

# fast build rule for target.
wan-cli/fast:
	$(MAKE) $(MAKESILENT) -f examples/cli/CMakeFiles/wan-cli.dir/build.make examples/cli/CMakeFiles/wan-cli.dir/build
.PHONY : wan-cli/fast

src/api/wan-api.o: src/api/wan-api.cpp.o
.PHONY : src/api/wan-api.o

# target to build an object file
src/api/wan-api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan-api.cpp.o
.PHONY : src/api/wan-api.cpp.o

src/api/wan-api.i: src/api/wan-api.cpp.i
.PHONY : src/api/wan-api.i

# target to preprocess a source file
src/api/wan-api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan-api.cpp.i
.PHONY : src/api/wan-api.cpp.i

src/api/wan-api.s: src/api/wan-api.cpp.s
.PHONY : src/api/wan-api.s

# target to generate assembly for a file
src/api/wan-api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan-api.cpp.s
.PHONY : src/api/wan-api.cpp.s

src/api/wan_config.o: src/api/wan_config.cpp.o
.PHONY : src/api/wan_config.o

# target to build an object file
src/api/wan_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_config.cpp.o
.PHONY : src/api/wan_config.cpp.o

src/api/wan_config.i: src/api/wan_config.cpp.i
.PHONY : src/api/wan_config.i

# target to preprocess a source file
src/api/wan_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_config.cpp.i
.PHONY : src/api/wan_config.cpp.i

src/api/wan_config.s: src/api/wan_config.cpp.s
.PHONY : src/api/wan_config.s

# target to generate assembly for a file
src/api/wan_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_config.cpp.s
.PHONY : src/api/wan_config.cpp.s

src/api/wan_i2v.o: src/api/wan_i2v.cpp.o
.PHONY : src/api/wan_i2v.o

# target to build an object file
src/api/wan_i2v.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_i2v.cpp.o
.PHONY : src/api/wan_i2v.cpp.o

src/api/wan_i2v.i: src/api/wan_i2v.cpp.i
.PHONY : src/api/wan_i2v.i

# target to preprocess a source file
src/api/wan_i2v.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_i2v.cpp.i
.PHONY : src/api/wan_i2v.cpp.i

src/api/wan_i2v.s: src/api/wan_i2v.cpp.s
.PHONY : src/api/wan_i2v.s

# target to generate assembly for a file
src/api/wan_i2v.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_i2v.cpp.s
.PHONY : src/api/wan_i2v.cpp.s

src/api/wan_loader.o: src/api/wan_loader.cpp.o
.PHONY : src/api/wan_loader.o

# target to build an object file
src/api/wan_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_loader.cpp.o
.PHONY : src/api/wan_loader.cpp.o

src/api/wan_loader.i: src/api/wan_loader.cpp.i
.PHONY : src/api/wan_loader.i

# target to preprocess a source file
src/api/wan_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_loader.cpp.i
.PHONY : src/api/wan_loader.cpp.i

src/api/wan_loader.s: src/api/wan_loader.cpp.s
.PHONY : src/api/wan_loader.s

# target to generate assembly for a file
src/api/wan_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_loader.cpp.s
.PHONY : src/api/wan_loader.cpp.s

src/api/wan_t2v.o: src/api/wan_t2v.cpp.o
.PHONY : src/api/wan_t2v.o

# target to build an object file
src/api/wan_t2v.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_t2v.cpp.o
.PHONY : src/api/wan_t2v.cpp.o

src/api/wan_t2v.i: src/api/wan_t2v.cpp.i
.PHONY : src/api/wan_t2v.i

# target to preprocess a source file
src/api/wan_t2v.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_t2v.cpp.i
.PHONY : src/api/wan_t2v.cpp.i

src/api/wan_t2v.s: src/api/wan_t2v.cpp.s
.PHONY : src/api/wan_t2v.s

# target to generate assembly for a file
src/api/wan_t2v.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/api/wan_t2v.cpp.s
.PHONY : src/api/wan_t2v.cpp.s

src/model.o: src/model.cpp.o
.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i
.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s
.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/name_conversion.o: src/name_conversion.cpp.o
.PHONY : src/name_conversion.o

# target to build an object file
src/name_conversion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/name_conversion.cpp.o
.PHONY : src/name_conversion.cpp.o

src/name_conversion.i: src/name_conversion.cpp.i
.PHONY : src/name_conversion.i

# target to preprocess a source file
src/name_conversion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/name_conversion.cpp.i
.PHONY : src/name_conversion.cpp.i

src/name_conversion.s: src/name_conversion.cpp.s
.PHONY : src/name_conversion.s

# target to generate assembly for a file
src/name_conversion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/name_conversion.cpp.s
.PHONY : src/name_conversion.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wan-cpp.dir/build.make CMakeFiles/wan-cpp.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ggml"
	@echo "... ggml-base"
	@echo "... ggml-cpu"
	@echo "... wan-cli"
	@echo "... wan-cpp"
	@echo "... zip"
	@echo "... src/api/wan-api.o"
	@echo "... src/api/wan-api.i"
	@echo "... src/api/wan-api.s"
	@echo "... src/api/wan_config.o"
	@echo "... src/api/wan_config.i"
	@echo "... src/api/wan_config.s"
	@echo "... src/api/wan_i2v.o"
	@echo "... src/api/wan_i2v.i"
	@echo "... src/api/wan_i2v.s"
	@echo "... src/api/wan_loader.o"
	@echo "... src/api/wan_loader.i"
	@echo "... src/api/wan_loader.s"
	@echo "... src/api/wan_t2v.o"
	@echo "... src/api/wan_t2v.i"
	@echo "... src/api/wan_t2v.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/name_conversion.o"
	@echo "... src/name_conversion.i"
	@echo "... src/name_conversion.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

